- hosts: localhost
  connection: local
  gather_facts: NO
  tasks:
    - name: Import VPC variables
      include_vars: vars/bastion_setup

    - name: Create Public ec2 key
      ec2_key:
        name: Public-key
        region: "{{region}}"
      register: key_out



