- hosts: localhost
  connection: local
  gather_facts: NO
  tasks:
    - name: Import VPC variables
      include_vars: vars/bastion_setup
    - name: Import VPC variables
      include_vars: vars/output_vars

    - name: Create Public ec2 key
      ec2_key:
        name: Public-key
        region: "{{region}}"
      register: key_out
  #  - debug:
      #  var: key_out
    - name: save private key as file public.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./public.pem"
        mode: 8608
      when: key_out.changed





