---
- name: local project stack
  hosts: localhost
  connection: local
  gather_facts: NO
  tasks:
    - name: Import Vpc Variables
      include_vars: vars/vpc-output_vars
    - name: Import project set up variables
      include_vars: vars/projectstacksetup
    - name: Create Key pair
      ec2_key:
        name: project key
        region: "{{region}}"
      register: key_out
    - name: save the key as a file key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./key.pem"
        mode: 8608
      when: key_out.changed
  #  - debug:
  #      var : key_out
    - name: Create sg for ELB
      ec2_group:
        name: projectELB_SG
        description: Allow  port 80 from  everywhere and all port within sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_block: 0.0.0.0/0
      register: Elbsg_out
    - name: Create sg for project stack
      ec2_group:
        name: Stack-sg
        description: allow port 22 from any where and all port with in sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{Elbsg_out.group_id}}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{Bastiosgid}}"
      register: projectstack_out
    - name: Update sg for its own sg id
      ec2_group:
        name: Stack-sg
        description: allow port 22 from any where and all port with in sg
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{projectstack_out.group_id}}"


















