---
- name: local project stack
  hosts: localhost
  connection: local
  gather_facts: NO
  tasks:
    - name: Import Vpc Variables
      include_vars: vars/vpc-output_vars
    - name: Import project set up variables
      include_vars: vars/projectstacksetup
    - name: Create Key pair
      ec2:
        name: project key
        region: "{{region}}"
      register: key_out
    - name: save the key as a file key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./key.pem"
        mode: 8608
      when: key_out.changed
    - debug:
        var : key_out





